# Generated by Django 4.2.4 on 2023-08-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("author", models.CharField(max_length=128)),
                ("inventory", models.PositiveIntegerField()),
                (
                    "cover",
                    models.CharField(
                        choices=[("SOFT", "Soft"), ("HARD", "Hard")],
                        max_length=4,
                    ),
                ),
                (
                    "daily_fee",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
            ],
        ),
    ]
